import "./globals.css";

import type { Metadata } from "next";
import { Patrick_Hand } from "next/font/google";
import localFont from "next/font/local";

const nuraFont = localFont({
  src: [
    {
      path: "../../public/fonts/nura/nura.ttf",
    },
  ],
  variable: "--font-nura",
});

const virgilFont = localFont({
  src: [
    {
      path: "../../public/fonts/virgil/virgil.woff2",
    },
  ],
  variable: "--font-virgil",
});

const patrickFont = Patrick_Hand({ weight: ["400"], subsets: ["latin"], variable: "--font-patrickhand" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${nuraFont.variable} ${virgilFont.variable} ${patrickFont.variable}`}>{children}</body>
    </html>
  );
}
