import "./globals.css";

import { Metadata } from "next";
import local from "next/font/local";
import { getServerSession } from "next-auth";

import AuthProvider from "@/components/AuthProvider";
import FontProvider from "@/components/FontProvider";
import Navbar from "@/components/Navbar";
import SignUpModal from "@/components/SignUpModal";
import authOptions from "@/libs/nextAuth/authOption";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="flex h-screen w-full flex-col bg-[#D9D9D9]   font-google">
        <>
          <AuthProvider session={session}>
            <FontProvider>
              <Navbar />
              <SignUpModal />
              {children}
            </FontProvider>
          </AuthProvider>
        </>
      </body>
    </html>
  );
}
