import "./globals.css";

import { Metadata } from "next";
import local from "next/font/local";

import AuthProvider from "@/components/AuthProvider";
import FontProvider from "@/components/FontProvider";
import Navbar from "@/components/Navbar";
import SignUpModal from "@/components/SignUpModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full bg-background px-4 text-text-1">
        <div className="mx-auto w-full max-w-[1240px]">
          <AuthProvider>
            <FontProvider>
              <Navbar />
              <SignUpModal />
              {children}
            </FontProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
